### ISSUE TITLE
Tips Filename convention

### ISSUE THREAD

**Issue by nhlm** [php-earth/php-tips#1]
I like to recommend to name the files by their publishing dates instead of number them one ofter another. The numbering should be later done by indexing them in a database.

Thanks.

**Comment by petk** [comment]
I agree, better to go with date keys:
`YYYY-MM-DD-N`
For example, `2017-04-15-1`

In case there are multiple tips added on the same day, the `N` is the number between 1 and 9.

For the database itself, I would keep as much information in this repository directly via YAML front matter instead for now. In case it will be required to go with a database, I'll refactor later more. Cheers.

Closing via a147858512a864966d6c304e24b5ac1654c681eb

**Comment by nhlm** [comment]
`YYYY-MM-DD_N`

**Comment by nhlm** [comment]
Alternatively:

https://prime.singularity.name/stardate/stardate-standard.pdf

`129.04-1.md`

**Comment by petk** [comment]
Reopening after discussion... Y-m-d dates are not a good pick...

**Comment by Maikuolan** [comment]
Providing a greater amount of information context with minimal effort is *usually* a good thing, and seeing as files must be named something anyhow, and a date versus an iterable number generally should be naturally ordered in the same way (assuming the right date format is chosen, of course), I'm in favour of using dates instead of a simple iterable number.

Using some variant of a standard `yyyy[._-]mm[._-]dd[._-]n+` or using stardates both sound good to me. Needless to say, `(mm?[._-]dd?|dd?[._-]mm?)[._-]yy{2|4}([._-]n+)?` would not follow the same natural ordering, and so, would not sound so good to me (*regex used as an aid here, to avoid writing needlessly long lists*). The suggestions actually made sound good though.

**Comment by petk** [comment]
Tips categorization set via 424508b2852c0241185d52bdd4eaee074faed29a

Closing this as resolved until further issues will arise.
